"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a$dm5b4q5bp&4_%8m&6*3mfxea%b#v)9bnfppkyz$=mmixt!b6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'user',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup',
    'corsheaders',
    'project_exchange',
    'shop',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
]

INTERNAL_IPS = ['127.0.0.1']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:5173", 
]


ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

from django.templatetags.static import static

UNFOLD = {
    "SITE_HEADER": "Стадиум",
    "SITE_SUBHEADER": "Панель управления",
    "DASHBOARD_CALLBACK": "project_exchange.views.dashboard_callback",
    "SIDEBAR": {
        "navigation": [
            {
                "title": "Навигация",
                "items": [
                    {
                        "title": "Дашборд",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ]
            },
            {
                "title": "Пользователь",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": "Пользователи",
                        "icon": "people",
                        "link": reverse_lazy("admin:user_customuser_changelist"),
                        "permission": lambda request: request.user.has_perm("user.view_customuser"),
                    },
                    {
                        "title": "Группы пользователей",
                        "icon": "groups",
                        "link": reverse_lazy("admin:user_usergroups_changelist"),
                        "permission": lambda request: request.user.has_perm("user.view_usergroups"),
                    },
                    {
                        "title": "Организации",
                        "icon": "enterprise",
                        "link": reverse_lazy("admin:user_organization_changelist"),
                        "permission": lambda request: request.user.has_perm("user.view_organization"),
                    },
                    {
                        "title": "Данные исполнителей",
                        "icon": "school",
                        "link": reverse_lazy("admin:user_executordata_changelist"),
                        "permission": lambda request: request.user.has_perm("user.view_executordata"),
                    },
                    {
                        "title": "Балансы",
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:user_balance_changelist"),
                        "permission": lambda request: request.user.has_perm("user.view_balance"),
                    },
                    {
                        "title": "Обращения",
                        "icon": "chat_info",
                        "link": reverse_lazy("admin:user_request_changelist"),
                        "permission": lambda request: request.user.has_perm("user.view_request"),
                    },
                ],
            },

            {
                "title": "Биржа проектов",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": "Проекты",
                        "icon": "task",
                        "link": reverse_lazy("admin:project_exchange_project_changelist"),
                        "permission": lambda request: request.user.has_perm("project_exchange.view_project"),
                    },
                    # {
                    #     "title": "Файлы проектов",
                    #     "icon": "file_present",
                    #     "link": reverse_lazy("admin:project_exchange_projectfiles_changelist"),
                    #     "permission": lambda request: request.user.has_perm("project_exchange.view_projectfiles"),
                    # },
                    {
                        "title": "Категории проектов",
                        "icon": "category",
                        "link": reverse_lazy("admin:project_exchange_categoryproject_changelist"),
                        "permission": lambda request: request.user.has_perm("project_exchange.view_categoryproject"),
                    },
                    {
                        "title": "Технологии проектов",
                        "icon": "stacks",
                        "link": reverse_lazy("admin:project_exchange_technology_changelist"),
                        "permission": lambda request: request.user.has_perm("project_exchange.view_technology"),
                    },
                    {
                        "title": "Отклики",
                        "icon": "add_comment",
                        "link": reverse_lazy("admin:project_exchange_response_changelist"),
                        "permission": lambda request: request.user.has_perm("project_exchange.view_response"),
                    },
                    {
                        "title": "Отзывы",
                        "icon": "thumbs_up_down",
                        "link": reverse_lazy("admin:project_exchange_feedback_changelist"),
                        "permission": lambda request: request.user.has_perm("project_exchange.view_feedback"),
                    },
                    {
                        "title": "Чаты",
                        "icon": "chat",
                        "link": reverse_lazy("admin:project_exchange_chat_changelist"),
                        "permission": lambda request: request.user.has_perm("project_exchange.view_exchange"),
                    },
                    # {
                    #     "title": "Сообщения чатов",
                    #     "icon": "mail",
                    #     "link": reverse_lazy("admin:project_exchange_chatmessages_changelist"),
                    #     "permission": lambda request: request.user.has_perm("project_exchange.view_chatmessages"),
                    # },
                    # {
                    #     "title": "Файлы сообщений",
                    #     "icon": "attach_email",
                    #     "link": reverse_lazy("admin:project_exchange_messagefiles_changelist"),
                    #     "permission": lambda request: request.user.has_perm("project_exchange.view_messagefiles"),
                    # },
                    # {
                    #     "title": "Пользователи чатов",
                    #     "icon": "3p",
                    #     "link": reverse_lazy("admin:project_exchange_chatusers_changelist"),
                    #     "permission": lambda request: request.user.has_perm("project_exchange.view_chatusers"),
                    # },
                ],
            },

            {
                "title": "Магазин",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": "Товары",
                        "icon": "package_2",
                        "link": reverse_lazy("admin:shop_product_changelist"),
                        "permission": lambda request: request.user.has_perm("shop.view_product"),
                    },
                    {
                        "title": "Категории товаров",
                        "icon": "category",
                        "link": reverse_lazy("admin:shop_categoryproduct_changelist"),
                        "permission": lambda request: request.user.has_perm("shop.view_categoryproduct"),
                    },
                    {
                        "title": "Корзины",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:shop_cart_changelist"),
                        "permission": lambda request: request.user.has_perm("shop.view_cart"),
                    },
                    # {
                    #     "title": "Товары в корзинах",
                    #     "icon": "shopping_cart_checkout",
                    #     "link": reverse_lazy("admin:shop_cartproduct_changelist"),
                    #     "permission": lambda request: request.user.has_perm("shop.view_cartproduct"),
                    # },
                    {
                        "title": "Заказы",
                        "icon": "receipt",
                        "link": reverse_lazy("admin:shop_order_changelist"),
                        "permission": lambda request: request.user.has_perm("shop.view_order"),
                    },
                    # {
                    #     "title": "Товары в заказах",
                    #     "icon": "receipt_long",
                    #     "link": reverse_lazy("admin:shop_orderproduct_changelist"),
                    #     "permission": lambda request: request.user.has_perm("shop.view_orderproduct"),
                    # },
                ],
            }
        ],
    },
}

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Chita'


USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'

AUTH_USER_MODEL = 'user.CustomUser'