# Generated by Django 6.0.2 on 2026-04-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('reques_status', models.CharField(choices=[('UNDER_CONSIDERATION', 'На рассмотрении'), ('REVIEWED', 'Рассмотрено')], default='UNDER_CONSIDERATION', max_length=30, verbose_name='Статус обращения')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-create_at'],
            },
        ),
    ]
