# Generated by Django 6.0.2 on 2026-04-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='reques_status',
            new_name='request_status',
        ),
    ]
