# Generated by Django 6.0.2 on 2026-04-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_rename_reques_status_request_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
