# Generated by Django 6.0.2 on 2026-04-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Фото'),
        ),
    ]
