# Generated by Django 6.0.2 on 2026-04-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_customuser_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='number_points',
            new_name='number_of_points',
        ),
    ]
