# Generated by Django 6.0.2 on 2026-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_rename_number_points_balance_number_of_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
    ]
