# Generated by Django 6.0.2 on 2026-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executordata',
            name='group',
        ),
        migrations.AddField(
            model_name='executordata',
            name='study_group',
            field=models.CharField(default=1, max_length=60, verbose_name='Учебная группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
