# Generated by Django 5.2.5 on 2025-09-08 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProducts',
            new_name='CartProduct',
        ),
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(1, 'Оформлен'), (2, 'Получен'), (3, 'Отменен')], default='Оформлен', max_length=40, verbose_name='Статус заказа'),
        ),
    ]
