# Generated by Django 5.2.5 on 2025-09-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_cartproducts_cartproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('A', 'Появится в будущем'), ('B', 'В наличии'), ('C', 'Отсутсвует')], max_length=40, verbose_name='Статус товара'),
        ),
    ]
