# Generated by Django 5.2.5 on 2025-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_status',
            field=models.CharField(choices=[('A', 'Доступен'), ('B', 'Недоступен')], max_length=40, verbose_name='Статус чата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('A', 'Оформлен'), ('B', 'Получен'), ('C', 'Отменен')], default='Оформлен', max_length=40, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('A', 'Поиск исполнителя'), ('B', 'В работе'), ('C', 'Завершена'), ('D', 'Отменена')], max_length=40, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_reward',
            field=models.CharField(choices=[('A', 'Бальное'), ('B', 'Денежное')], max_length=40, verbose_name='Тип вознаграждения'),
        ),
    ]
