# Generated by Django 5.2.5 on 2025-09-10 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chat_chat_status_alter_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessages',
            new_name='ChatMessage',
        ),
        migrations.RenameModel(
            old_name='MessageFiles',
            new_name='MessageFile',
        ),
    ]
