# Generated by Django 5.2.5 on 2025-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_chatmessages_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_status',
            field=models.CharField(choices=[('A', 'Доступен'), ('B', 'Недоступен')], default='Доступен', max_length=40, verbose_name='Статус чата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadlines',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Сроки(количество дней)'),
        ),
    ]
