# Generated by Django 5.2.5 on 2025-09-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_chat_chat_status_alter_task_deadlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_status',
            field=models.CharField(choices=[('A', 'Доступен'), ('B', 'Недоступен')], default='A', max_length=1, verbose_name='Статус чата'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='number_stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Количество звезд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('A', 'Оформлен'), ('B', 'Получен'), ('C', 'Отменен')], default='A', max_length=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('A', 'Появится в будущем'), ('B', 'В наличии'), ('C', 'Отсутствует')], max_length=1, verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='response',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadlines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сроки(количество дней)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('A', 'Поиск исполнителя'), ('B', 'В работе'), ('C', 'Завершена'), ('D', 'Отменена')], default='A', max_length=1, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_reward',
            field=models.CharField(choices=[('A', 'Бальное'), ('B', 'Денежное')], max_length=1, verbose_name='Тип вознаграждения'),
        ),
    ]
