# Generated by Django 5.2.5 on 2025-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_order_total_amount_alter_chat_chat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_status',
            field=models.CharField(choices=[('AVAILABLE', 'Доступен'), ('UNAVAILABLE', 'Недоступен')], default='A', max_length=30, verbose_name='Статус чата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CREATED', 'Оформлен'), ('RECEIVED', 'Получен'), ('CANCELED', 'Отменен')], default='A', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('FUTURE', 'Появится в будущем'), ('AVAILABLE', 'В наличии'), ('UNAVAILABLE', 'Отсутствует')], max_length=30, verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('LOOKING_FOR_EXECUTOR', 'Поиск исполнителя'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELED', 'Отменена')], default='A', max_length=30, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_reward',
            field=models.CharField(choices=[('POINTS', 'Бальное'), ('CASH', 'Денежное')], max_length=30, verbose_name='Тип вознаграждения'),
        ),
    ]
