# Generated by Django 5.2.5 on 2025-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_chat_chat_status_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(through='main.TaskTag', to='main.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('LOOKING_FOR_EXECUTOR', 'Поиск исполнителя'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELED', 'Отменена')], default='POINTS', max_length=30, verbose_name='Статус задачи'),
        ),
    ]
