# Generated by Django 6.0.2 on 2026-05-20 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_project_icon/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проекта',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.IntegerField(default=0, verbose_name='Последнее прочитанное сообщение')),
            ],
            options={
                'verbose_name': 'Пользователи чата',
                'verbose_name_plural': 'Пользователи чатов',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MessageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл в сообщении',
                'verbose_name_plural': 'Файлы в сообщениях',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(choices=[('UNDER_INSPECTION', 'На проверке'), ('LOOKING_FOR_EXECUTOR', 'Поиск исполнителя'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELED', 'Отменена')], default='UNDER_INSPECTION', max_length=30, verbose_name='Статус проекта')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cash_reward', models.BooleanField(default=False, verbose_name='Денежное вознаграждение')),
                ('number_of_points', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('due_date', models.DateField(verbose_name='Дата сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': (models.Case(models.When(project_status='IN_PROGRESS', then=0), models.When(project_status='LOOKING_FOR_EXECUTOR', then=1), models.When(project_status='UNDER_INSPECTION', then=2), models.When(project_status='COMPLETED', then=3), models.When(project_status='CANCELED', then=4), default=5, output_field=models.IntegerField()), '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файлы проекта',
                'verbose_name_plural': 'Файлы проектов',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отклика')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время сообщения')),
                ('changed', models.BooleanField(default=False, verbose_name='Изменено')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project_exchange.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'ordering': ('-id',),
            },
        ),
    ]
