# Generated by Django 6.0.2 on 2026-03-16 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проекта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.chatmessages', verbose_name='Сообщение чата')),
            ],
            options={
                'verbose_name': 'Файл в сообщении',
                'verbose_name_plural': 'Файлы в сообщениях',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(choices=[('UNDER_INSPECTION', 'На проверке'), ('LOOKING_FOR_EXECUTOR', 'Поиск исполнителя'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELED', 'Отменена')], default='UNDER_INSPECTION', max_length=30, verbose_name='Статус проекта')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cash_reward', models.BooleanField(default=False, verbose_name='Денежное вознаграждение')),
                ('number_of_points', models.IntegerField(blank=True, null=True, verbose_name='Количество баллов')),
                ('due_date', models.IntegerField(verbose_name='Дата сдачи')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения')),
                ('category_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_exchange.categoryproject', verbose_name='Категория проекта')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_set', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('executors', models.ManyToManyField(related_name='executor_set', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
                ('moderators', models.ManyToManyField(related_name='moderators_set', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы')),
                ('technologies', models.ManyToManyField(to='project_exchange.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Количество звезд')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файлы проекта',
                'verbose_name_plural': 'Файлы проектов',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время отклика')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'executor')},
            },
        ),
    ]
