# Generated by Django 6.0.2 on 2026-05-20 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='messagefiles',
            name='chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_exchange.chatmessages', verbose_name='Сообщение чата'),
        ),
        migrations.AddField(
            model_name='project',
            name='category_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_exchange.categoryproject', verbose_name='Категория проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executor_projects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AddField(
            model_name='project',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderator_projects', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='project_exchange.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_exchange.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='response',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='response',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exchange.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technology_projects', to='project_exchange.technology', verbose_name='Технологии'),
        ),
        migrations.AlterUniqueTogether(
            name='chatusers',
            unique_together={('chat', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('project', 'executor')},
        ),
    ]
