# Generated by Django 6.0.2 on 2026-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_points',
            field=models.IntegerField(default=0, verbose_name='Количество баллов'),
        ),
    ]
