# Generated by Django 6.0.2 on 2026-05-28 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='custom_category_project',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Другая категория проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_technologies',
            field=models.JSONField(blank=True, default=list, verbose_name='Другие технологии'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('UNDER_INSPECTION', 'На проверке'), ('LOOKING_FOR_EXECUTOR', 'Поиск исполнителя'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершен'), ('CANCELED', 'Отменен')], default='UNDER_INSPECTION', max_length=30, verbose_name='Статус проекта'),
        ),
        migrations.AlterField(
            model_name='response',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_responses', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
