# Generated by Django 6.0.2 on 2026-04-20 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0002_alter_project_due_date_alter_project_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executor_set', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='project',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderators_set', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='project_exchange.technology', verbose_name='Технологии'),
        ),
    ]
