# Generated by Django 6.0.2 on 2026-05-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custom_technologies',
            field=models.TextField(blank=True, null=True, verbose_name='Другие технологии'),
        ),
    ]
