# Generated by Django 6.0.2 on 2026-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0003_alter_project_executors_alter_project_moderators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefiles',
            name='file',
            field=models.FileField(upload_to='chat_files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(upload_to='project_files/', verbose_name='Файл'),
        ),
    ]
