# Generated by Django 6.0.2 on 2026-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0004_alter_messagefiles_file_alter_projectfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время сообщения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отклика'),
        ),
    ]
