# Generated by Django 6.0.2 on 2026-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0004_alter_project_custom_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number_of_points',
            field=models.IntegerField(choices=[(50, 50), (125, 125), (200, 200)], default=50, verbose_name='Количество баллов'),
        ),
    ]
