# Generated by Django 6.0.2 on 2026-04-21 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0005_alter_chatmessages_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='project_exchange.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project_exchange.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='number_stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд'),
        ),
        migrations.AlterField(
            model_name='messagefiles',
            name='chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_exchange.chatmessages', verbose_name='Сообщение чата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_exchange.categoryproject', verbose_name='Категория проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executor_projects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='project',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderator_projects', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technology_projects', to='project_exchange.technology', verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_exchange.project', verbose_name='Проект'),
        ),
    ]
