# Generated by Django 6.0.2 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exchange', '0007_alter_project_number_of_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'ordering': ('-id',), 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='chatusers',
            options={'ordering': ('-id',), 'verbose_name': 'Пользователь чата', 'verbose_name_plural': 'Пользователи чата'},
        ),
        migrations.AlterModelOptions(
            name='messagefiles',
            options={'ordering': ('-id',), 'verbose_name': 'Файл в сообщении', 'verbose_name_plural': 'Файлы в сообщении'},
        ),
        migrations.AlterModelOptions(
            name='projectfiles',
            options={'ordering': ('-id',), 'verbose_name': 'Файлы проекта', 'verbose_name_plural': 'Файлы проекта'},
        ),
        migrations.AlterField(
            model_name='chatusers',
            name='last_read_message_id',
            field=models.IntegerField(default=0, verbose_name='ID последнего прочитанного сообщение'),
        ),
    ]
